//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReferenceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceClient.IServiceHello")]
    public interface IServiceHello {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/HelloWorld", ReplyAction="http://tempuri.org/IServiceHello/HelloWorldResponse")]
        string HelloWorld(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/HelloWorld", ReplyAction="http://tempuri.org/IServiceHello/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(string login, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHelloChannel : WebApplication1.ServiceReferenceClient.IServiceHello, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHelloClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReferenceClient.IServiceHello>, WebApplication1.ServiceReferenceClient.IServiceHello {
        
        public ServiceHelloClient() {
        }
        
        public ServiceHelloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHelloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHelloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHelloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld(string login, string pass) {
            return base.Channel.HelloWorld(login, pass);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(string login, string pass) {
            return base.Channel.HelloWorldAsync(login, pass);
        }
    }
}
