//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReferenceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceClient.IServiceHello")]
    public interface IServiceHello {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/HelloAccount", ReplyAction="http://tempuri.org/IServiceHello/HelloAccountResponse")]
        WcfService1.Models.Account HelloAccount(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHello/HelloAccount", ReplyAction="http://tempuri.org/IServiceHello/HelloAccountResponse")]
        System.Threading.Tasks.Task<WcfService1.Models.Account> HelloAccountAsync(string login, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHelloChannel : WebApplication1.ServiceReferenceClient.IServiceHello, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHelloClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReferenceClient.IServiceHello>, WebApplication1.ServiceReferenceClient.IServiceHello {
        
        public ServiceHelloClient() {
        }
        
        public ServiceHelloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHelloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHelloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHelloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfService1.Models.Account HelloAccount(string login, string pass) {
            return base.Channel.HelloAccount(login, pass);
        }
        
        public System.Threading.Tasks.Task<WcfService1.Models.Account> HelloAccountAsync(string login, string pass) {
            return base.Channel.HelloAccountAsync(login, pass);
        }
    }
}
